#!/usr/bin/env bash
# Extract RK3576 NPU hardware values from local source trees.
# Writes notes/rk3576-npu-values.md.
# Usage: bash extract/extract-npu-values.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LNEXT="/home/parallels/Desktop/rock4d_package/kernel-build/linux-next"
BL31="/home/parallels/Desktop/bl3-rk3576"
OUT="$REPO_ROOT/notes/rk3576-npu-values.md"
PROV="$REPO_ROOT/notes/provenance.md"

for tree in "$LNEXT" "$BL31"; do
    if [[ ! -d "$tree" ]]; then
        echo "ERROR: source tree not found: $tree" >&2; exit 1
    fi
done

mkdir -p "$(dirname "$OUT")"

header() { printf '\n## %s\n\n' "$1"; }
row()    { printf '| %-40s | %-12s | %-10s | %s\n' "$1" "$2" "$3" "$4"; }
hr()     { printf '| %s | %s | %s | %s\n' "$(printf '%0.s-' {1..40})" "$(printf '%0.s-' {1..12})" "$(printf '%0.s-' {1..10})" "$(printf '%0.s-' {1..50})"; }

{
cat <<'HEADER'
# RK3576 NPU Hardware Values

Generated by `extract/extract-npu-values.sh`. All values tagged CONFIRMED or UNVERIFIED.

HEADER

# ── Power domains ──────────────────────────────────────────────────────────────
header "Power Domains"
PFILE=$(find "$LNEXT/include/dt-bindings/power" -name "*rk3576*" | head -1)
echo "Source: \`${PFILE#$LNEXT/}\`"
echo
printf '| %-40s | %-12s | %-10s | %s\n' "Symbol" "Value" "Status" "Source"
hr
while IFS= read -r line; do
    sym=$(echo "$line" | grep -o 'RK3576_PD_[A-Z0-9_]*' || true)
    val=$(echo "$line" | grep -o '[0-9]*$' || true)
    lno=$(grep -n "$sym" "$PFILE" 2>/dev/null | head -1 | cut -d: -f1 || true)
    [[ -n "$sym" && -n "$val" ]] && row "$sym" "$val" "CONFIRMED" "${PFILE#$LNEXT/}:$lno"
done < <(grep "RK3576_PD_NPU" "$PFILE" 2>/dev/null || true)

# ── Clocks ─────────────────────────────────────────────────────────────────────
header "Clocks (CRU)"
CFILE=$(find "$LNEXT/include/dt-bindings/clock" -name "*rk3576*" | head -1)
echo "Source: \`${CFILE#$LNEXT/}\`"
echo
printf '| %-40s | %-12s | %-10s | %s\n' "Symbol" "Value" "Status" "Source"
hr
for sym in ACLK_RKNN0 ACLK_RKNN1 HCLK_RKNN_ROOT CLK_RKNN_DSU0 PCLK_NPUTOP_ROOT \
            HCLK_RKNN_CBUF ACLK_RKNN_CBUF SCMI_CLK_GPU; do
    val=$(grep -o "define ${sym}[[:space:]]*[0-9]*" "$CFILE" 2>/dev/null | awk '{print $3}' || true)
    lno=$(grep -n "define $sym" "$CFILE" 2>/dev/null | head -1 | cut -d: -f1 || true)
    [[ -n "$val" ]] && row "$sym" "$val" "CONFIRMED" "${CFILE#$LNEXT/}:$lno"
done
echo
echo "Note: SCMI NPU clock = CLK_RKNN_DSU0 (mapped in BL31 SCMI table)"
echo "Source: \`${BL31#$BL31/}tfa/plat/rockchip/rk3576/scmi/rk3576_clk.c:1101\`"

# ── Resets ─────────────────────────────────────────────────────────────────────
header "Resets (CRU)"
RFILE=$(find "$LNEXT/include/dt-bindings/reset" -name "*rk3576*" | head -1)
echo "Source: \`${RFILE#$LNEXT/}\`"
echo
printf '| %-40s | %-12s | %-10s | %s\n' "Symbol" "Value" "Status" "Source"
hr
for sym in SRST_A_RKNN0 SRST_A_RKNN0_BIU SRST_L_RKNN0_BIU \
            SRST_A_RKNN1 SRST_A_RKNN1_BIU SRST_L_RKNN1_BIU \
            SRST_A_RKNN_CBUF SRST_H_RKNN_CBUF SRST_A_RKNNTOP_BIU SRST_H_RKNNTOP_BIU; do
    val=$(grep -o "define ${sym}[[:space:]]*[0-9]*" "$RFILE" 2>/dev/null | awk '{print $3}' || true)
    lno=$(grep -n "define $sym" "$RFILE" 2>/dev/null | head -1 | cut -d: -f1 || true)
    [[ -n "$val" ]] && row "$sym" "$val" "CONFIRMED" "${RFILE#$LNEXT/}:$lno"
done
echo
echo "Note: No SRST_H_RKNN0 / SRST_H_RKNN1 in rk3576 (unlike rk3588)."
echo "srst_h binding slot is UNVERIFIED for rk3576."

# ── NPU GRF ────────────────────────────────────────────────────────────────────
header "NPU GRF (syscon)"
DTS="$LNEXT/arch/arm64/boot/dts/rockchip/rk3576.dtsi"
GRF_ADDR=$(grep "npu_grf:" "$DTS" | grep -o '@[0-9a-f]*' | tr -d '@' || true)
GRF_LNO=$(grep -n "npu_grf:" "$DTS" | head -1 | cut -d: -f1 || true)
printf '| %-40s | %-12s | %-10s | %s\n' "Symbol" "Value" "Status" "Source"
hr
row "npu_grf base (NPUGRF_BASE)" "0x${GRF_ADDR}" "CONFIRMED" "arch/arm64/boot/dts/rockchip/rk3576.dtsi:$GRF_LNO"
BL31_GRF=$(grep "NPUGRF_BASE" "$BL31/tfa/plat/rockchip/rk3576/rk3576_def.h" | grep -o '0x[0-9a-f]*' || true)
BL31_LNO=$(grep -n "NPUGRF_BASE" "$BL31/tfa/plat/rockchip/rk3576/rk3576_def.h" | head -1 | cut -d: -f1 || true)
row "NPUGRF_BASE (BL31 cross-check)" "$BL31_GRF" "CONFIRMED" "tfa/plat/rockchip/rk3576/rk3576_def.h:$BL31_LNO"

# ── PVTPLL_NPU ─────────────────────────────────────────────────────────────────
header "PVTPLL NPU (SCMI)"
PVT=$(grep "PVTPLL_NPU_BASE" "$BL31/tfa/plat/rockchip/rk3576/rk3576_def.h" | grep -o '0x[0-9a-f]*' || true)
PVT_LNO=$(grep -n "PVTPLL_NPU_BASE" "$BL31/tfa/plat/rockchip/rk3576/rk3576_def.h" | head -1 | cut -d: -f1 || true)
printf '| %-40s | %-12s | %-10s | %s\n' "Symbol" "Value" "Status" "Source"
hr
row "PVTPLL_NPU_BASE" "$PVT" "CONFIRMED" "tfa/plat/rockchip/rk3576/rk3576_def.h:$PVT_LNO"

# ── OPP rates ──────────────────────────────────────────────────────────────────
header "NPU OPP Rates"
SCMI_C="$BL31/tfa/plat/rockchip/rk3576/scmi/rk3576_clk.c"
RATES=$(sed -n '/rk3576_npu_rates\[\]/,/^};/p' "$SCMI_C" | grep -o '[0-9]*000000[0-9]*' | sort -u)
RATES_LNO=$(grep -n "rk3576_npu_rates" "$SCMI_C" | head -1 | cut -d: -f1)
echo "Source: \`tfa/plat/rockchip/rk3576/scmi/rk3576_clk.c:$RATES_LNO\`"
echo
echo "Rates (Hz): $(echo $RATES | tr '\n' ' ')"
echo
echo "PVTPLL table (rate_hz, ring_sel, length, length_frac):"
PVTPLL_LNO=$(grep -n "rk3576_npu_pvtpll_table" "$SCMI_C" | head -1 | cut -d: -f1)
sed -n "/rk3576_npu_pvtpll_table\[\]/,/sentinel/p" "$SCMI_C" | grep "ROCKCHIP_PVTPLL" | \
    sed 's/.*ROCKCHIP_PVTPLL(\(.*\))/\1/' | while IFS=',' read -r r s l lf rest; do
        printf '  - %10s Hz  ring=%-3s len=%-4s frac=%s\n' \
               "$(echo $r | xargs)" "$(echo $s | xargs)" "$(echo $l | xargs)" "$(echo $lf | xargs)"
    done

# ── RKNN core registers (CONFIRMED from vendor kernel) ─────────────────────────
header "RKNN Core Registers (CONFIRMED from vendor kernel)"
cat <<'UNREG'
> Confirmed against Radxa RK3576 vendor kernel (linux-6.1-stan-rkr5.1) at
> /home/parallels/Desktop/rk3576-vendor-kernel/arch/arm64/boot/dts/rockchip/rk3576.dtsi
> Vendor models the NPU as a single `rknpu: npu@27700000` (reg <0x27700000 0x8000>,
> <0x27708000 0x8000>) with one `rknpu_mmu: iommu@27702000` holding 4 banks.
> MMU = core_base + 0x2000 (NOT +0x9000). NPU probe confirmed on HW build #17.

UNREG
printf '| %-40s | %-12s | %-10s | %s\n' "Node" "Address" "Status" "Basis"
hr
row "rknn_core_0 (pc)"    "0x27700000" "CONFIRMED" "vendor rk3576.dtsi:2414 (npu0 block base)"
row "rknn_core_0 (cna)"   "0x27701000" "CONFIRMED" "Offset +0x1000 (pc VERSION reg @0x0)"
row "rknn_core_0 (core)"  "0x27703000" "CONFIRMED" "Offset +0x3000"
row "rknn_mmu_0 (bankA)"  "0x27702000" "CONFIRMED" "vendor rk3576.dtsi:2648 (core0+0x2000)"
row "rknn_mmu_0 (bankB)"  "0x27702100" "CONFIRMED" "vendor rk3576.dtsi:2649"
row "rknn_core_1 (pc)"    "0x27710000" "CONFIRMED" "0x27700000 + 0x10000"
row "rknn_core_1 (cna)"   "0x27711000" "CONFIRMED" "Offset +0x1000"
row "rknn_core_1 (core)"  "0x27713000" "CONFIRMED" "Offset +0x3000"
row "rknn_mmu_1 (bankA)"  "0x2770a000" "CONFIRMED" "vendor rk3576.dtsi:2650 (core1+0x2000)"
row "rknn_mmu_1 (bankB)"  "0x2770a100" "CONFIRMED" "vendor rk3576.dtsi:2651"

# ── RKNN interrupts (CONFIRMED from vendor kernel) ─────────────────────────────
header "RKNN Interrupts (CONFIRMED from vendor kernel)"
cat <<'UNREG'
> Confirmed from vendor rk3576.dtsi. Both the NPU core and its MMU share the
> per-core IRQ line. Earlier 344/345 guess was wrong (345 = dsi@27d80000).
UNREG
echo
printf '| %-40s | %-12s | %-10s | %s\n' "Core" "GIC_SPI" "Status" "Basis"
hr
row "rknn_core_0 + mmu_0 interrupt" "247" "CONFIRMED" "vendor rk3576.dtsi:2416 npu0_irq, :2652 npu0_mmu"
row "rknn_core_1 + mmu_1 interrupt" "248" "CONFIRMED" "vendor rk3576.dtsi:2417 npu1_irq, :2653 npu1_mmu"

# ── QoS nodes ──────────────────────────────────────────────────────────────────
header "QoS Nodes"
echo "Source: \`arch/arm64/boot/dts/rockchip/rk3576.dtsi\`"
echo
printf '| %-40s | %-12s | %-10s | %s\n' "Node" "Address" "Status" "Source line"
hr
grep "qos_npu" "$DTS" | while IFS= read -r line; do
    addr=$(echo "$line" | grep -o '@[0-9a-f]*' | tr -d '@' || true)
    name=$(echo "$line" | grep -o 'qos_[a-z0-9_]*:' | tr -d ':' || true)
    lno=$(grep -n "${name}:" "$DTS" 2>/dev/null | head -1 | cut -d: -f1 || true)
    [[ -n "$name" && -n "$addr" ]] && row "$name" "0x${addr}" "CONFIRMED" "rk3576.dtsi:$lno" || true
done || true

} > "$OUT"

# ── Also emit provenance.md ───────────────────────────────────────────────────
sed '1s/.*/# RK3576 NPU Provenance/' "$OUT" > "$PROV"

echo "Written: $OUT"
echo "Written: $PROV"
