#!/usr/bin/env python3
# Copyright (c) 2026 Jiaxing Hu <gahing@gahingwoo.com>
# SPDX-License-Identifier: GPL-2.0
"""
Compute the vendor's depthwise layer by hand and find its output in the capture.

Round 56 replaced a flattering number with an honest one. mn_dw1 matches 9 of
32 channels but only ONE of those has a reference that varies; the other eight
are a saturated output agreeing with a saturated reference. mn_dw25 is 2 of
1024, not 432. The regular shapes are the control and they came back 128 of 128
COMPUTED, so the metric is not merely pessimistic.

What did improve, and is not an artefact: on the shipped configuration mn_dw1
has ZERO channels where the hardware output is constant while the reference
varies, against 14 on the round 53 baseline. The depthwise conv now fires on
every channel. The numbers it produces are wrong.

Everything upstream of the numbers is verified against the vendor: the weight
buffer 288 of 288 lanes, the fourteen depthwise registers, the record layout,
and A and C at 32 of 32 channels each. What has never been checked is the
OUTPUT end, and the capture can check it, because the vendor's depthwise run is
fully determined here:

    input     bo3, which CNA 0x1088 points at, a ramp
    weights   generated by sv_pairs.py
    bias      generated by sv_pairs.py
    requant   DPU 0x40b0 and 0x40b4 from the register stream

So the accumulator is computable exactly, and the captured output is the answer
key for how the accumulator becomes bytes. That is the one convention this
driver still chooses rather than derives: mesa writes C in Q4 with its own
OUT_CVT shift, the vendor writes Q14 with a shift two larger, and forcing
mesa to the vendor's Q14 rails the output.

CONTROL: the same computation is run for sv_rgu, whose regular conv this driver
already reproduces byte for byte. If the accumulator cannot be matched to the
captured output THERE, the model of the pipeline is wrong and nothing the
depthwise half says can be read.

DECISION RULE, written before the run:
  control's output found, and an affine map from the accumulator explains it
      -> read the same map for depthwise and compare with what mesa emits
  control not found
      -> either the output BO is not what is assumed or the input is not the
         ramp, and both are checkable before anything else is believed
"""
import os
import re
import struct
import sys

import numpy as np

from extract_regcmd import TARGETS, decode


def bos(path):
    out = []
    for ln in open(os.path.join(path, "meta.txt")):
        m = re.match(r"bo idx=(\d+) handle=\d+ dma=0x([0-9a-f]+) \S+ size=(\d+)", ln)
        if m:
            out.append((int(m.group(1)), int(m.group(2), 16), int(m.group(3))))
    return out


def first_run(path):
    d = open(os.path.join(path, "bo01.bin"), "rb").read()
    n = len(d) // 8
    w = struct.unpack("<%dQ" % n, d[:n * 8])
    i = 0
    while i < n:
        if ((w[i] >> 48) & 0xffff) in TARGETS:
            j = i
            while j < n and ((w[j] >> 48) & 0xffff) in TARGETS:
                j += 1
            if j - i >= 40:
                return [decode(w[k]) for k in range(i, j)]
            i = j
        else:
            i += 1
    return []


def regs(path):
    m = {}
    for tgt, val, reg in first_run(path):
        m.setdefault(reg, val)
    return m


def known():
    rng = np.random.RandomState(7)
    b = (rng.randn(32) * 0.05).astype(np.float32)
    wdw = (rng.randn(32, 1, 3, 3) * 0.08).astype(np.float32)
    wrg = (rng.randn(32, 32, 3, 3) * 0.08).astype(np.float32)
    return b, wdw, wrg


def asym_perchannel(flat):
    lo = flat.min(axis=1, keepdims=True)
    hi = flat.max(axis=1, keepdims=True)
    s = (hi - lo) / 255.0
    zp = np.rint(-lo / s) - 128
    return np.clip(np.rint(flat / s) + zp, -128, 127).astype(np.int8), \
        s.reshape(-1), zp.reshape(-1)


def buf(path, idx):
    return np.frombuffer(open(os.path.join(path, f"bo{idx:02d}.bin"), "rb").read(),
                         dtype=np.uint8)


def accumulate_dw(x, w_q, w_zp, in_zp, H=112, W=112, C=32):
    """The depthwise accumulator, sum (x - in_zp)(w - w_zp), SAME padding."""
    xi = x.reshape(H, W, C).astype(np.int64) - in_zp
    acc = np.zeros((H, W, C), dtype=np.int64)
    for ky in range(3):
        for kx in range(3):
            sh = np.zeros_like(xi)
            ys, ye = max(0, 1 - ky), min(H, H + 1 - ky)
            xs, xe = max(0, 1 - kx), min(W, W + 1 - kx)
            sh[ys:ye, xs:xe] = xi[ky - 1 + ys:ky - 1 + ye, kx - 1 + xs:kx - 1 + xe]
            tap = (w_q[:, ky, kx].astype(np.int64) - w_zp.astype(np.int64))
            acc += sh * tap[None, None, :]
    return acc


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "../dirty/vendorcap-dw-2026-08-10"
    b, wdw, wrg = known()

    for tag in ("sv_rgu", "sv_dwu"):
        path = os.path.join(root, tag)
        bl = bos(path)
        r = regs(path)
        print(f"\n=== {tag} ===")
        print(f"  DPU 0x40b0 {r.get(0x40b0, 0):#010x}  0x40b4 "
              f"{r.get(0x40b4, 0):#010x} (shift {r.get(0x40b4, 0)})  "
              f"0x40b8 {r.get(0x40b8, 0):#010x}")
        for idx, dma, size in bl:
            v = buf(path, idx)
            nz = int((v != 0).sum())
            print(f"  bo{idx} size {size:8d}  nonzero {nz:8d}  "
                  f"distinct {len(np.unique(v)):3d}  first "
                  f"{' '.join(f'{x:02x}' for x in v[:8])}")

    # The depthwise half, computed.
    path = os.path.join(root, "sv_dwu")
    q, sc, zp = asym_perchannel(wdw.reshape(32, 9))
    q = q.reshape(32, 3, 3)
    x = buf(path, 3)
    if len(x) != 112 * 112 * 32:
        print("\n  bo3 is not 112x112x32, stopping")
        return
    print("\n=== sv_dwu: the accumulator, computed from the capture's own input ===")
    acc = accumulate_dw(x.view(np.int8), q, zp, in_zp=-128)
    print(f"  accumulator range {acc.min()} .. {acc.max()}")
    print(f"  per-channel means, first 6: "
          f"{[int(v) for v in acc.reshape(-1, 32).mean(axis=0)[:6]]}")

    bias_q = np.rint(b.astype(np.float64) / ((250.0 / 255.0) * sc))
    tot = acc + bias_q.astype(np.int64)[None, None, :]
    print(f"  with bias, range {tot.min()} .. {tot.max()}")

    # Which captured buffer holds the answer, and under what affine map?
    for idx, dma, size in bos(path):
        v = buf(path, idx)
        if size < tot.size:
            continue
        for off in (0,):
            cand = v[off:off + tot.size].reshape(112, 112, 32).astype(np.float64)
            if cand.std() == 0:
                continue
            f = tot.reshape(-1).astype(np.float64)
            g = cand.reshape(-1)
            cc = np.corrcoef(f, g)[0, 1]
            print(f"  bo{idx}+{off}: correlation with (accumulator + bias) "
                  f"{cc:+.5f}")


if __name__ == "__main__":
    main()
